sudo: required

language: python
python:
  - 3.6


matrix:
  include:
    - compiler: gcc
      before_install:
        - pip install numpy numba
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - git clone https://github.com/plures/xnd.git
        - cd ndtypes
        - python3 setup.py install --local=$PWD/../python
        - cd ../xnd
        - python3 setup.py install --local=$PWD/../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
        - python3 -m pip install numpy numba
      before_script:
        - export CC=clang
        - git clone https://github.com/plures/ndtypes.git
        - git clone https://github.com/plures/xnd.git
        - cd ndtypes
        - python3 setup.py install --local=$PWD/../python
        - cd ../xnd
        - python3 setup.py install --local=$PWD/../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
        - conda install --yes numpy
        - conda install --yes numba
        - conda install --yes -c plures/label/dev ndtypes
        - conda install --yes -c plures/label/dev xnd
      script:
        - cd gumath
        - git fetch --unshallow
        - conda build .conda/libgumath -c plures/label/dev
        - conda build .conda/gumath -c plures/label/dev
        - export LIBGUMATH=`conda build --output .conda/libgumath -c plures/label/dev`
        - export GUMATH=`conda build --output .conda/gumath -c plures/label/dev`

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build=3.3.0
        - conda install --yes anaconda-client
        - conda install --yes numpy
        - conda install --yes numba
        - conda install --yes -c plures/label/dev ndtypes
        - conda install --yes -c plures/label/dev xnd
      script:
        - cd gumath
        - git fetch --unshallow
        - conda build .conda/libgumath -c plures/label/dev
        - conda build .conda/gumath -c plures/label/dev
        - export LIBGUMATH=`conda build --output .conda/libgumath -c plures/label/dev`
        - export GUMATH=`conda build --output .conda/gumath -c plures/label/dev`
